### ISSUE TITLE
Use npm scripts

### ISSUE THREAD

**Issue by ocombe** [amcdnl/systemjs-test#1]
You might want to simplify the install process by using the npm scripts: `npm install` could execute the `bower install` and the `jspm install`, you just need to add this to your package.json :

``` js
"scripts": {
    "postinstall": "bower install && jspm install"
}
```

You could add other scripts for common gulp tasks as well, take a look [at this](https://docs.npmjs.com/misc/scripts).
This way you can use the local bower / jspm / gulp from the node_modules folder without the need to install them globally :)

**Comment by amcdnl** [comment]
Good idea ... I want to move the bower to jspm anyway.

**Comment by amcdnl** [comment]
Lets move to JSPM vs Bower.  @marjan-georgiev
