### ISSUE TITLE
extract the builder into its own npm module

### ISSUE THREAD

**Issue by lookfirst** [amcdnl/systemjs-test#10]
The builder code is pretty magically awesome. I can't even fathom how much effort it was to build that. How about extracting that into it's own npm module?

**Comment by lookfirst** [comment]
https://github.com/lookfirst/systemjs-route-bundler

added you as a collaborator

**Comment by amcdnl** [comment]
Thanks!  :) ... we were actually talking about doing this, mind if you transfer me the repo so our team can maintain it closer?  

We have a bunch of holes and optimizations we need to fix before its ready for prime release.  We also need to add tests and docs ...

**Comment by lookfirst** [comment]
Happily done. =)

I made a few changes to it that don't all show up in commits...
1. abstracted out a few hard coded places into config variables
2. added an `RSVP.on 'error'` handler that gets called when a route exists, but the files on disk don't. I felt like this was a pretty hacky way to deal with things because it was a catch all, but I couldn't figure out how to get the code to handle that case directly so that I could display a better error message. The Promise.all() would just silently fail otherwise.

Finally, if you setup a npm account and tell me what it is, I'll also transfer over the npm package of this too...

https://www.npmjs.com/package/systemjs-route-bundler

**Comment by amcdnl** [comment]
FYI - Here is the link https://github.com/Swimlane/systemjs-route-bundler

my npm is https://www.npmjs.com/~amcdnl

**Comment by lookfirst** [comment]
:+1: 

I'm also working on a re-do of your gulpfile for this project to try to simplify things a bit and fix a couple other issues I found in there. I'll publish that soon too.

I'm super excited about your seed project as it finally gets rid of requirejs and adds good testability. Thanks so much for doing all this work.

**Comment by lookfirst** [comment]
Added you as an owner to npm

**Comment by amcdnl** [comment]
@lookfirst Ya, we had require and after we did our last release I just said enough is enough!  It was such a dramatic undertaking and so many bleeding technologies thought it would be best to publish it on Github for collab.  After we got done, the build was such a pain and with lazy-loading modules couldn't be read so we decided to go with this totally automated build system which is pretty nice but not totally there yet.

On that note, I'm going to update the name to `angular-systemjs-seed` ... 

If you just make PRs to the main repo, I'll merge them in no problem.  thanks again for helping!

**Comment by lookfirst** [comment]
@amcdnl Well, my main change is to switch to coffeescript for the gulp file, so I can understand if you don't want that. :smile:

**Comment by amcdnl** [comment]
Well, I'm not really a big coffee script guy haha

**Comment by lookfirst** [comment]
No worries... most people aren't. =)
