### ISSUE TITLE
fix ngAnnotate use

### ISSUE THREAD

**Issue by darcnite3000** [amcdnl/systemjs-test#23]
https://github.com/olov/ng-annotate#explicit-annotations-with-nginject

``` js
$futureStateProvider.stateFactory('load',($q, $ocLazyLoad, futureState)=>{
  'ngInject';

  return $q((resolve,reject)=>{
    //code here
  });
});
```

**Comment by amcdnl** [comment]
Interesting, did not know that.

**Comment by amcdnl** [comment]
this shouldn't be an issue on latest though.  Since we manually annotated the items.

**Comment by lookfirst** [comment]
I tried all sorts of variations of that and couldn't get it to work right. =( The one I didn't try was putting the `'ngInject'` inside of the method like @darcnite3000 has done, I thought it had to occur above it based on the docs. =(

**Comment by lookfirst** [comment]
I just tested it and his fix works, but honestly, I don't see it as that much of a stylistic benefit. =( It is far more clear to just write out the injection.

**Comment by amcdnl** [comment]
I agree, don't love the special syntax

**Comment by darcnite3000** [comment]
I was mainly showing how it could work without manually annotating.
In the end it comes down to preference.

**Comment by amcdnl** [comment]
@darcnite3000 - absolutely and thanks for the share.
