### ISSUE TITLE
Handle Template Cache w/ ES6

### ISSUE THREAD

**Issue by amcdnl** [amcdnl/systemjs-test#24]
With the new version of gulphtml2js we can define a custom header template, this would allow us to use ES6 better.  https://github.com/marklagendijk/gulp-ng-html2js/pull/9

so templates might be like:

```
export var {templateFileName} = angular.module('....')
```

then you could use it like:

```
import {myTemplateFile} from './template.tpl';
```

**Comment by lookfirst** [comment]
Smoother is to just `export default angular.module('...')`, then you just write:

`import myTemplateFile from './template.tpl'`

Sadly the main developer rejected my pull request. =(

https://github.com/marklagendijk/gulp-ng-html2js/issues/15
https://github.com/marklagendijk/gulp-ng-html2js/pull/16

**Comment by lookfirst** [comment]
https://github.com/marklagendijk/gulp-ng-html2js/pull/17

**Comment by amcdnl** [comment]
Ya, default would be better but wasn't sure on a way to get the template module named elegantly dynamically.

**Comment by lookfirst** [comment]
Doesn't matter cause the object returned from angular.module has a .name property. Works great.

**Comment by amcdnl** [comment]
Fixed by latest push using template.
