### ISSUE TITLE
Move bower components to jspm

### ISSUE THREAD

**Issue by amcdnl** [amcdnl/systemjs-test#25]
Per #1 , we should move bower components to jspm to simplify things.

**Comment by lookfirst** [comment]
Oh, I just did this... so nice!

**Comment by dmackerman** [comment]
I'm getting started with JSPM and SystemJS and a little lost on some stuff. @lookfirst do you have an example somewhere?

**Comment by lookfirst** [comment]
@dmackerman Welcome to the future! =) It'll get less confusing soon, but this is all pretty cutting edge stuff these days. I do plan on writing some step-by-step example documentation soon. Looking into using material design for the docs. =)

Here is a couple projects to get started.
1. This swimlane project that you just commented on is where I started. Then I created my own fork of it and improved it a whole bunch...
2. https://github.com/lookfirst/systemjs-seed
3. https://github.com/lookfirst/module-a -- A smaller example based off my [yeoman generator](https://github.com/lookfirst/generator-systemjs).

Hope that helps!

**Comment by amcdnl** [comment]
@dmackerman check out this - https://github.com/angular/material-start/tree/es6

**Comment by lookfirst** [comment]
Funny, I've been looking at that too... I'm going to convert that to work on the seed project using my yeoman generator as the basis. I'd like to setup something that allows me to create documentation easily and then use that to document the whole process. How meta!

**Comment by marjan-georgiev** [comment]
This is complete on the latest master branch.
