### ISSUE TITLE
multiple declaration of routes

### ISSUE THREAD

**Issue by lookfirst** [amcdnl/systemjs-test#26]
Right now, there is a `routes.json` file and in that file, we declare the top level routes. However, these same routes are also declared in say `login.js` module configuration. It seems a bit DRY. Is there a way to clean this up?

**Comment by amcdnl** [comment]
That's an oversight good catch

**Comment by amcdnl** [comment]
We have to declare the route again with the full details of the route.  This is what actually registers it, the top level json routes are just for knowing where to get it.

**Comment by lookfirst** [comment]
Understood. Was hoping that there was a better way.
