### ISSUE TITLE
require('babel/external-helpers')

### ISSUE THREAD

**Issue by iksose** [amcdnl/systemjs-test#31]
https://github.com/jspm/jspm-cli/issues/633

Luckily I found that issue, I couldn't run this repo until I included `require('babel/external-helpers')` at the top of app.js

Also btw this repo is incredible

**Comment by Hypercubed** [comment]
I had to do the same.  I added `import 'babel/external-helpers';`

**Comment by amcdnl** [comment]
Ya, this was a recent change in JSPM.  I need to update the project to use that.  PR welcome ;)

**Comment by Hypercubed** [comment]
I submitted the PR but the solution was thanks to @iksose .
