### ISSUE TITLE
Installing materialize using jspm on the seed

### ISSUE THREAD

**Issue by zeeshanjan82** [amcdnl/systemjs-test#38]
I am trying to install materialize css library using jspm command on the seed and it doesn't work, I have attached the screenshot
![jspm](https://cloud.githubusercontent.com/assets/8342604/8446288/e39b2062-1fc5-11e5-95fe-d4b3211ad47e.png)

**Comment by amcdnl** [comment]
Thats a issue with their package.  I would reach out to the JSPM channel on Gitter for advice.

**Comment by zeeshanjan82** [comment]
Thanks @amcdnl  the issue is fixed.
