### ISSUE TITLE
Html files not getting copied

### ISSUE THREAD

**Issue by zeeshanjan82** [amcdnl/systemjs-test#40]
I was trying to run the gulp release command and I have the following html task in the gulp file which is directly taken from the seed project:

gulp.task('html', function () {
  return gulp.src(path.templates)
    .pipe(cache('html'))
    .pipe(plumber())
    .pipe(changed(path.output, { extension: '.html' }))
    .pipe(htmlMin({
      empty: true,
      spare: true,
      quotes: true
    }))
    .pipe(ngHtml2Js({
      template: "import angular from 'angular';\n" +
        "export default angular.module('<%= moduleName %>', []).run(['$templateCache', function($templateCache) {\n" +
        "   $templateCache.put('<%= template.url %>',\n    '<%= template.prettyEscapedContent %>');\n" +
        "}]);\n"
    }))
    .pipe(babel(compilerOptions))
    .pipe(gulp.dest(path.output))
    .pipe(browserSync.reload({ stream: true }));
});

However the task runs fine but I cannot find any html files in the dest folder.

**Comment by amcdnl** [comment]
whats your output `.pipe(gulp.dest(path.output))` ?

**Comment by zeeshanjan82** [comment]
Thanks @amcdnl  the issue got fixed itself. I just ran the gulp release several times and then I could find the html files in dest folder.
