### ISSUE TITLE
Error in the release

### ISSUE THREAD

**Issue by zeeshanjan82** [amcdnl/systemjs-test#41]
I am getting following error when deploying the release. Actually I am using NodeWebkit and making a release using this seed project
Potentially unhandled rejection [2] ReferenceError: Error loading "app/login/login" at file:///C:/Users/ADMINI~1/AppData/Local/Temp/nw9104_8193/dist/app/login/login.js
babelHelpers is not defined

**Comment by marjan-georgiev** [comment]
This should be fixed now. Please verify

**Comment by zeeshanjan82** [comment]
Thanks @marjan-georgiev  I will check and revert back.
