### ISSUE TITLE
production config error

### ISSUE THREAD

**Issue by DominicBoettger** [amcdnl/systemjs-test#42]
Since i reinstalled my node_modules with npm install SITUATION=production gulp run fails with

```

[20:27:37] 'routeBundler' errored after 18 ms
[20:27:37] TypeError: baseURL should only be configured once and must be configured first.
```

I tried to use all the versions i used previously but  i think one of the modules in gulp helpers node_modules dir is causing this issue. They are not fixed to specific version, just added a ^1.2.3

Any idea what's causing this issue and how it can be solved?

**Comment by marjan-georgiev** [comment]
I just updated the seed project. Could you check if it's still failing for you?

**Comment by DominicBoettger** [comment]
Thanks, but as i changed a lot of stuff i think the error is caused by my modifications. Now i get the error that some files can't be found. It tries to find the files without the file extension... I think i have to look for the problem in my modifications. You can close the issues if you want.
