### ISSUE TITLE
Materialize Installation Issue`

### ISSUE THREAD

**Issue by zeeshanjan82** [amcdnl/systemjs-test#48]
I am trying to install the latest version of Mateiralize from NPM https://www.npmjs.com/package/materialize-css . I am able to install it and when I reference the materialize-css@0.97.1/dist/js/materialize file inside my system.config.js I get 404 errors for  hammer.js

I am not sure why I am getting these errors.
![untitled-2](https://cloud.githubusercontent.com/assets/8342604/10189939/f491465e-6786-11e5-8126-3934f1ad9280.png)

**Comment by zeeshanjan82** [comment]
https://github.com/Swimlane/angular-systemjs-seed/issues/48

**Comment by amcdnl** [comment]
This is a systemjs / jspm configuration issue.
