### ISSUE TITLE
Clear cache on logout

### ISSUE THREAD

**Issue by zeeshanjan82** [amcdnl/systemjs-test#55]
I am facing some issues when I implement logout feature. Currently I am just clearing some session data which I maintain myself and then redirect user to the login state, however I have noticed as I am using socket.io when the socket.io event is fired even when I am logged out still I am able to receive that event because the data persists inside the services even when we have logged out. Is there any recommended way to implement logout feature in the seed?
I think it might be related to templateCache which needs to be cleared when we are logging out?

**Comment by amcdnl** [comment]
Logout highly depends on implementation.
