### ISSUE TITLE
jspm inject changes all paths

### ISSUE THREAD

**Issue by morgs32** [amcdnl/systemjs-test#56]
I'm trying to `jspm inject handlebars` for example, and it appears to make ALL my npm and github paths point to the remote.
Before:

```
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
```

Then: `jspm inject handlebars`

After:

```
  paths: {
    "github:*": "https://github.jspm.io/*",
    "npm:*": "https://npm.jspm.io/*"
  },
```

**Comment by marjan-georgiev** [comment]
Are you trying to install handlebars? Try `jspm install handlebars` instead

**Comment by morgs32** [comment]
No, I was hasty and should have given some more context. I'm on a project where in production we need to have _some_ of our modules on CDN and some installed.  I was hoping that `jspm inject` would add the complete path to just that module.

**Comment by marjan-georgiev** [comment]
I'd say that's a jspm issue then.

You could try adding the path manually, otherwise try asking the question in the jspm repo or in their gitter chat room.
