### ISSUE TITLE
Facing Strange PATH Error

### ISSUE THREAD

**Issue by zeeshanjan82** [amcdnl/systemjs-test#67]
I am using this seed project and suddenly I am facing this strange error on when running the compiled app:.
![error](https://cloud.githubusercontent.com/assets/8342604/19716618/6de269de-9b7a-11e6-980d-54abf399ce85.png)
I think I have updated the JSPM or systemjs-route-bundler and after that I got this error.

**Comment by amcdnl** [comment]
It doesn't work on latest versions. We have switched to webpack so we are phasing this project out.
