### ISSUE TITLE
release overwrites index.html

### ISSUE THREAD

**Issue by lookfirst** [amcdnl/systemjs-test#8]
I tend to shy away from modifying files that are under source control during a release. Maybe instead of modifying index.html inline, we copy it into dist and make everything relative to that?

**Comment by amcdnl** [comment]
Ya, I was on the fence about that too.  For me, the only thing that does this is the CI and when I'm testing but its not optimal.  Ya, I was thinking it might be best to do a index.dist.html or something or maybe put it in the dist?

**Comment by lookfirst** [comment]
Yea, a `index.tpl.html` is a good enough solution for now and then add a `.gitignore` for `index.html`. Putting it in `dist` would be difficult because it would require changing paths to things in a lot of places.

When I do build systems, I generally try to just make a folder like `dist` or `target` or `build` and then build everything in there and make everything relative to that folder. It makes doing the clean and packaging tasks a lot simpler because everything I need is in one place.

**Comment by amcdnl** [comment]
closing since #20 has a better fix idea
